### ISSUE TITLE
Never get a push notification yet everything is set up correctly 

### ISSUE THREAD

**Issue by Skytek65** [c99koder/wear-imessage#1]

**Comment by c99koder** [comment]
Are you able to send a push notification from the Terminal?

$ curl --header "Authorization: key=API_KEY" -F registration_id="REG_ID" -F data.service="test" -F data.handle="test" -F data.name="test" -F data.msg="test" -F data.type="msg" https://android.googleapis.com/gcm/send

(fill in your API key and GCM registration ID)

If not, then something's wrong with your GCM configuration.  If it works, then either the AppleScript handler isn't enabled or isn't working with whatever version of iMessage you have installed.

The app hasn't been updated to support Doze, so if you're on Marshmallow then you'll only get notifications if the device is awake.

**Comment by Skytek65** [comment]
Okay so its coming back as 
<HTML>
<HEAD>
<TITLE>Unauthorized</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1>Unauthorized</H1>

<H2>Error 401</H2>

</BODY>
</HTML>

But I have GCM enabled on the account so im not too sure what im doing wrong

**Comment by Skytek65** [comment]
Which API key do I use because there are three different ones?
Server key (auto created by Google Service)
Android key (auto created by Google Service)
Imessage(Project)

If I use the Server Key then I get this error: Error=MismatchSenderId

**Comment by c99koder** [comment]
use the Server key

**Comment by Skytek65** [comment]
So when I use the server key I get this error though Error=MismatchSenderId. I copied and pasted the key from the app and verified it is correct!

**Comment by c99koder** [comment]
Make sure you set the project number correctly in the Android app.  It
should be a number, not the "project ID".  You can get the project number
from https://console.cloud.google.com/

**Comment by Skytek65** [comment]
That would probably be the issue thanks very much! Have a great one!

-Skyler

**Comment by Skytek65** [comment]
Does this work on the latest version of OS X?

**Comment by c99koder** [comment]
I don't know, I don't use iMessage anymoore

**Comment by Skytek65** [comment]
So I got everything up and working, except for voice replies! I get this error when sending back a reply, do you know what it means?

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at dirname (path.js:1326:5)
    at execute (/Users/Sky/Downloads/wear-imessage-master/server/node_modules/node-osascript/lib/index.js:24:52)
    at Object.module.exports.execute (/Users/Sky/Downloads/wear-imessage-master/server/node_modules/node-osascript/lib/index.js:64:5)
    at /Users/Sky/Downloads/wear-imessage-master/server/server.js:66:19
    at Layer.handle [as handle_request](/Users/Sky/Downloads/wear-imessage-master/server/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/Sky/Downloads/wear-imessage-master/server/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/Sky/Downloads/wear-imessage-master/server/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request](/Users/Sky/Downloads/wear-imessage-master/server/node_modules/express/lib/router/layer.js:82:5)
    at /Users/Sky/Downloads/wear-imessage-master/server/node_modules/express/lib/router/index.js:267:22

**Comment by c99koder** [comment]
Looks like the node-osascript module needs to be updated, you can get the latest version from https://github.com/FWeinb/node-osascript

**Comment by Skytek65** [comment]
Your the bomb thanks!

-Skyler

**Comment by Skytek65** [comment]
Working 100%
